# THIS YAML SETTING IS USED AS A BASE TO PRODUCE THE 'PREPROCESSING.YAML' ONE.
# THIS IT IS MEANT TO BE USED AS A STARTING POINT AND DOCUMENTATION ONE (see all the different choises a user has).

LOADER:
  src_data:
    - FUNSD
    # - NAF
    # - CUSTOM
FEATURES:
  add_embs: False
  add_visual: False
  add_eweights: False
GRAPHS:
  edge_type:
    - fully
    # - knn
    # - visibility
  data_type:
    - img
    # - pdf