INFO:
  f1-macro: 0.5423
  f1-micro: 0.6211
  features: false
  split: 0
  total_params: 9604
  val_loss: 0.7864165306091309
MODEL:
  dropout: 0.0
  hidden_dim: 64
  name: GCN
  num_layers: 3
TRAIN:
  batch_size: 134
  epochs: 1000
  lr: 0.01
  weight_decay: 0.0005
